
## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://193.112.103.61:3306/mtbsm?characterEncoding=utf8&useSSL=false
    username: root
    password: wangxiang@
    driver-class-name: com.mysql.jdbc.Driver
    ##pool
    maxIdle: 20
    minIdle: 10
    maxWait: 9000
    initialSize: 5
    validationQuery: SELECT 1
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 600000
  ##redis缓存
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3S
  freemarker:
    charset: UTF-8

## Mybatis 配置
mybatis:
  mapperLocations: classpath*:mapper/relational/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

pagehelper:
  helperDialect: mysql
  closeConn: true
  supportMethodsArguments: true
  reasonable: true
  params: count=countSql

## token的配置
## timeout过期时间，120分钟
mtbsm:
  token:
    timeout: 120
    name: mttoken
server:
  port: 8090
  servlet:
    context-path: /v1
